### ISSUE TITLE
add note about node v6 required

### ISSUE THREAD

**Issue by Flet** [ungoldman/hi8#1]
May want to add a note that v6 is required:

Attempting to run in v4:

``` bash
/Users/flet/.nvm/versions/node/v4.2.6/lib/node_modules/hi8/bin.js:18
let proc = spawn(electron, [ hi8 ], { stdio: 'inherit' })
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by ungoldman** [comment]
Thanks for catching that! It's a bit dumb of me to require node 6 for one instance of `let` so I just simplified the syntax in `bin.js`. Should work fine on older versions of node now.
