### ISSUE TITLE
無法運行。

### ISSUE THREAD

**Issue by exsystem** [ungoldman/hi8#9]
最新版brew安裝後，在以前從未安裝過npm的情況下根據首頁說明安裝了npm，然後
當運行 `hi8`命令後直接報異常了，如下：
```
child_process.js:430
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received function wrappedCwd
    at normalizeSpawnArguments (child_process.js:430:11)
    at Object.spawn (child_process.js:546:13)
    at Function.module.exports.daemon (/usr/local/lib/node_modules/hi8/node_modules/daemon/index.js:50:31)
    at module.exports (/usr/local/lib/node_modules/hi8/node_modules/daemon/index.js:25:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/hi8/bin.js:8:3)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by ungoldman** [comment]
I'm sorry, I cannot read Chinese! 

Google translate has translated your message as follows:

> After installing the latest version of brew, install npm according to the homepage instructions without installing npm before, then
> When running the hi8 command, an exception is reported directly, as follows

I have not encountered this error before, but it's possible a breaking change was introduced into node:

https://github.com/nodejs/node/commit/20fd12310f3c82dbd45bc2161fa0a73bf823fe9e

I don't have time to investigate this week but hope this at least helps give you a clue to what the problem might be. Best of luck!

**Comment by exsystem** [comment]
好的，謝謝。
